### PR TITLE
Moving $OSNAME checks to compile time

### PR DESCRIPTION
**Pull request by ap**
Since `$OSNAME` never changes at runtime, there is no reason to do string comparisons with it more than once, so this puts the results of the comparisons into constants: it adds a new constant for the `MSWin32` check and (much less importantly, but while we’re there, why not) turns the `PATH` sub into a constant based on the `freebsd` check.

Not only does this stop the string comparison being done over and over again, but in fact, Perl knows that an `if`/`else` with a constant condition will always run one or the other branch, so it will compile out the entire conditional along with the non-taken branch. Using a constant therefore means that no checking at all is done at runtime.

### CODE REVIEW

**Comment by david-dick** [comment]
I'm trying to keep my modules to obey perlcritic -1, so the string evals are an issue for me.  Would you have any issue with the attached patch to your fork?
[without_eval.txt](https://github.com/david-dick/crypt-urandom/files/14071474/without_eval.txt)

**Comment by ap** [comment]
That does maintain the comparisons being done just once at compile time, but it defeats the constant folding and branch elimination. For `PATH` it’s not a real issue, but that’s only the bonus while-we’re-there part of the patch; for `OS_WIN32` it matters.

Now because of all the `sub WHATEVER () { }` constants I presumed that you are avoiding `use constant` (as generally do I). But if you’re not averse to it, you can instead set up those constants like this:

````diff
diff --git i/lib/Crypt/URandom.pm w/lib/Crypt/URandom.pm
--- i/lib/Crypt/URandom.pm
+++ w/lib/Crypt/URandom.pm
@@ -22,13 +22,14 @@ sub W2K_MAJOR_VERSION { return 5; }
 sub W2K_MINOR_VERSION { return 0; }
 sub SINGLE_QUOTE      { return q[']; }

-sub PATH {
+use constant OS_WIN32 => $OSNAME eq 'MSWin32';
+use constant PATH => do {
     my $path = '/dev/urandom';
     if ( $OSNAME eq 'freebsd' ) {
         $path = '/dev/random';    # FreeBSD's /dev/random is non-blocking
     }
-    return $path;
-}
+    $path;
+};

 my $_initialised;
 my $_context;
@@ -37,7 +38,7 @@ my $_rtlgenrand;
 my $_urandom_handle;

 sub _init {
-    if ( $OSNAME eq 'MSWin32' ) {
+    if ( OS_WIN32 ) {
         require Win32;
         require Win32::API;
         require Win32::API::Type;
@@ -137,7 +138,7 @@ sub _urandom {
         _init();
         $_initialised = $PROCESS_ID;
     }
-    if ( $OSNAME eq 'MSWin32' ) {
+    if ( OS_WIN32 ) {
         my $buffer = chr(0) x $length;
         if ($_cryptgenrandom) {

````

Though in that case you’d probably want to go whole hog and move all of the other constants over as well.

Would that work for you?

**Comment by ap** [comment]
Oh. I’m being silly. Those subs aren’t constants. They all return constant literal values, but they don’t have any prototype and they all use the `return` keyword, both of which factors prevent them from compiling as constants. The question is then whether you prefer to fix them to be constants by writing them like this:

````perl
sub CRYPT_SILENT      () { 64 }               # hex 40
sub PROV_RSA_FULL     () { 1 }
sub VERIFY_CONTEXT    () { 4_026_531_840 }    # hex 'F0000000'
sub W2K_MAJOR_VERSION () { 5 }
sub W2K_MINOR_VERSION () { 0 }
sub SINGLE_QUOTE      () { q['] }
````
… or like this:
````perl
use constant CRYPT_SILENT      => 64;               # hex 40
use constant PROV_RSA_FULL     => 1;
use constant VERIFY_CONTEXT    => 4_026_531_840;    # hex 'F0000000'
use constant W2K_MAJOR_VERSION => 5;
use constant W2K_MINOR_VERSION => 0;
use constant SINGLE_QUOTE      => q['];
````
(Not sure why it’s highlighted inconsistently.)

P.S.: In case you’re not familiar with why I’m going on about this, you can use
````
perl -MO=Deparse lib/Crypt/URandom.pm
````
to see a reconstruction of the code after perl has compiled it, as it will be executed. If you do that with the versions with vs without constants, you’ll see why I’m going on about this. (Note that constant declarations aren’t visible to Deparse, so they won’t show in its output, but that doesn’t mean they’re not there. Deparse has its limitations.) You’ll find all those constant names replaced with the respective constant values, as well as entire expressions involving only constants replaced with their result (e.g. string concatenations), meaning perl won’t spend any runtime repeating work that always produces the same result. With my other changes included, that extends to omitting either the Win32 or non-Win32 branches entirely, depending on the value of `$OSNAME`.

**Comment by ap** [comment]
Ping?

**Comment by david-dick** [comment]
sorry about my absence.  I'm aiming to get some time to think about this on the weekend.

**Comment by david-dick** [comment]
What about this change?
[critic.txt](https://github.com/david-dick/crypt-urandom/files/14309234/critic.txt)

**Comment by ap** [comment]
Sure. Uses actual constants, so works for me. What I’m after is the compile-time code elimination enabled by constants, so having you introduce them in whatever way you are happy with is the only thing I’m hoping for. The happier, the better for me.

**Pull request merged**
